### ISSUE TITLE
Sekcja fit

### ISSUE THREAD

**Issue by KlepsydraHG** [KlepsydraHG/StronaRWD#2]
https://imgur.com/a/fwQsDE3 - o to konkretnie chodzi

**Comment by NataliaTI** [comment]
@KlepsydraHG 

- [x] musimy jeszcze dostosować tę sekcję do projektu graficznego
- [x] https://prnt.sc/20x09q1 - tutaj powinniśmy się na coś zdecydować albo grid albo float, łączenie tych dwóch własności nie ma wiele sensu ;) proponuję usunąć obie własności stąd i dodać `display:flex` do elemnetu `.imgs` - tak jest najprościej ;)
- [x] klasy nie spełniają wytycznych BEM - stosujemy tam podwójne podkreślenie, nie pojedyncze, łączą w sobie j.p. z j.ang. i dodatkowo są zbyt abstrakcyjne (zbyt ogólne), powinny nieco precyzyjniej opisywać, za który element na stronie odpowiadają - ale bez przesady w drugą stronę ;)
- [x] https://prnt.sc/20x0cdz ten margines dolny, który jest odpowiedzialny za odstęp pomiędzy sekcjami, lepiej byłoby zdefiniować dla kontenera nadrzędnego sekcji, czyli w tym przypadku do `.imgs` - w ten sposób łatwiej będzie go znaleźć innym programistom i będzie wyliczony tylko raz, zamiast 4 razy ;)
- [x] jeśli na projekcie tekst wyświetla się drukowanymi literami, w HTML zapiszmy go normalnie i dodajmy `text-transform:uppercase` w CSS
- [x] https://prnt.sc/20x0ec9 - to podkreślenie jest w tej chwili zrobione poprzez border w divie `imgs_bottext`, natomiast gdy spojrzymy na projekt to w pierwszym odczuciu podkreślenie widzimy pod nazwą posta (nagłówkiem) i jak się tak chwilę zastanowić to logicznie tekst pod nazwą wpisu jest tylko uzupełnieniem, dodatkiem, który ma zachęcić do przeczytania posta, więc istnieje taka możliwość, że przy niektórych postach nie będzie tego tekstu, bo sam post bez niego jest w pełni wartościowy, a w sytuacji, w której nie ma podpisu pod nazwą posta, kiepsko będzie wyglądała nazwa bez podkreślenia, które zniknie nam przy okazji tego, że nie ma tekstu po spodem ;)
- [x] zastanów się proszę czy wszystkie style w `.imgs_bottext` są potrzebne - starajmy się zawsze osiągnąć maksymalną elastyczność w elementach, przewidujmy co się wydarzy, gdy tekst będzie krótszy czy dłuższy, itd. ;)
- [x] każdy tag `img` w HTML musi mieć zdefiniowany atrybut `alt` - w przypadku zdjęć powinien on opisywać co znajduje się na zdjęciu (lub przynajmniej zawierać nazwę artykułu do którego odnosi się zdjęcie), a w przypadku ozdobników graficznych powinien być pusty

**Comment by KlepsydraHG** [comment]
Prawdopodobnie sekcja fit zostanie napisana od nowa

Edit: a jednak nie :)
