### ISSUE TITLE
Przykładowy post na blogu

### ISSUE THREAD

**Issue by KlepsydraHG** [KlepsydraHG/StronaRWD#3]

**Comment by NataliaTI** [comment]
@mikolajczake 

- [x] każdy tag `img` w HTML musi mieć zdefiniowany atrybut `alt` - w przypadku zdjęć powinien on opisywać co znajduje się na zdjęciu (lub przynajmniej zawierać nazwę artykułu do którego odnosi się zdjęcie), a w przypadku ozdobników graficznych powinien być pusty
- [x] poproszę o nazwy klas, zgodne z konwencją nazewnictwa BEM oraz nadające znaczenie poszczególnym elementom, zgodnie z ich faktyczną rolą na stronie :)
- [x] poniższe dwa style wyglądają na zbędne, clear nie jest potrzebny bo nie będziemy używali float na stronie ;) a height w tym przypadku trochę niepotrzebnie ogranicza wysokość posta, jeśli w którymś z postów będzie mniej tekstu to pozostanie przez to pusta przestrzeń, a jeśli w którymś będzie więcej tekstu to tekst zacznie wychodzić poza obszar posta - więc same kłopoty z tego w tym przypadku ;)
![obraz](https://user-images.githubusercontent.com/65622759/143932433-cd53c18c-0f72-4da1-ab6f-4af8bb8f850f.png)

- [x] jeden z tych divów jest zbędny, oba pełnią rolę kontenera na pojedynczy post
![obraz](https://user-images.githubusercontent.com/65622759/143932604-1a869081-c80b-4d05-b47e-bd7458ec6830.png)

- [x] zdjęcie oraz nazwa wpisu powinny linkować do widoku wybranego posta - na ten moment gdy nie mamy linków może dać chwilowo `href="#"`
- [x] liczę na jakiś fajny efekt po najechaniu myszką na zdjęcie posta ;)
- [x] ikonki social media pod postem i w stopce to w zasadzie dokładnie to samo wizualnie, może dogadałbyś się z kolegą od stopki i opracujecie jakieś wspólne klasy i style dla tych ikonek tak byśmy mogli wykorzystać je w obu miejscach? ;)
![obraz](https://user-images.githubusercontent.com/65622759/143933077-b94692f2-db14-40c6-928b-02f9d3a29adb.png)

- [ ] wizualnie całość wymaga jeszcze dostosowania do projektu graficznego
- [ ] do zrobienia RWD
