### ISSUE TITLE
Przyciski "Newer Post" i "Older Post" na dole maina

### ISSUE THREAD

**Issue by KlepsydraHG** [KlepsydraHG/StronaRWD#5]

**Comment by NataliaTI** [comment]
@jacusdestroyer 

- [x] popracuj proszę nad lepszym ułożeniem tych elementów za pomocą flex - tak jak pokazywałam na jednym ze spotkań (i nie używamy float! ;))
- [x] nazwy klasy wymagają poprawki wg tego co pisałam w #6

**Comment by NataliaTI** [comment]
Dostosujmy proszę jeszcze wizualnie do projektu graficznego :)
