### ISSUE TITLE
Bottom

### ISSUE THREAD

**Issue by KlepsydraHG** [KlepsydraHG/StronaRWD#6]
https://imgur.com/a/tHOB6c5 - chodzi o tą część

**Comment by NataliaTI** [comment]
@jacusdestroyer 

- [x] poproszę o nazwy klas, zgodne z konwencją nazewnictwa BEM oraz nadające znaczenie poszczególnym elementom, zgodnie z ich faktyczną rolą na stronie :)
- [x] każdy tag `img` w HTML musi mieć zdefiniowany atrybut `alt` - w przypadku zdjęć powinien on opisywać co znajduje się na zdjęciu (lub przynajmniej zawierać nazwę artykułu do którego odnosi się zdjęcie), a w przypadku ozdobników graficznych powinien być pusty
- [x] https://prnt.sc/2103sfa - nie stosujemy stylów liniowych poza nielicznymi wyjątkami, miejscem na style jest plik CSS 
- [x] dla linków prowadzących do stron zewnętrznych powinniśmy ustawić zawsze atrybut `target="_blank"`, aby otwierały się one w nowym oknie (to mamy, super!) oraz atrybut `rel="noopener nofollow"`, który sprawia że po pierwsze nie dajemy dostępu stronie zewnętrznej, na którą odsyłamy użytkownika do naszej strony poprzez kod JS (wiodące przeglądarki domyślnie już blokują to zachowanie) oraz dodatkowo zapobiega przekierowywaniu ruchu robotów internetowych na zewnętrzne strony, co źle wpływa na pozycjonowanie strony w wynikach wyszukiwania np. Google
- [x] szerokość linka do social media jaką aktualnie widzi przeglądarka jest taka jak na obrazku poniżej, co sprawia że klikając w wizualnie pustą przestrzeń pomiędzy ikonkami przeniosę się na zewnętrzną stronę - użytkownik może nie być gotowy na takie zachowanie, widzi ikonkę w kółku i wyłącznie ona powinna linkować
![obraz](https://user-images.githubusercontent.com/65622759/143929580-8879f0e3-059b-4c13-af58-730f00e0d478.png)

- [x] nie znam takiego elementu w HTML jak `<bottom>` ale jeśli przekonasz mnie, że istnieje i jest zgodny ze specyfikacją, to może zostać ;)
- [x] nie używajmy znaczników `<br>` i `<hr>` jeśli chcemy osiągnąć wizualnie odstęp lub linię, mamy do tego CSS. Te znaczniki zostawmy dla edytorów treści wysiwyg ;)
- [x] trzeba popracować jeszcze odrobinę nad dostosowanie wdrożenia do projektu graficznego ;)
- [x] ten styl chyba nie jest obecnie używany - i dobrze, ale nie ma potrzeby trzymać go w pliku CSS ;)
![obraz](https://user-images.githubusercontent.com/65622759/143931114-0d67ff5a-7641-4068-b1f7-7c14cfa0d9a1.png)



Ps. Bardzo ładne zastosowanie flexów i bardzo fajny pomysł z ikonkami w formie fonta 👍

**Comment by NataliaTI** [comment]
- [x] https://prnt.sc/22ke014 - https://prnt.sc/22keeys - na projekcie odstępy pomiędzy tymi elementami są zdecydowanie mniejsze, dostosujmy proszę na wdrożeniu ;)
- [x] kolor kreski również wymaga jeszcze dostosowania do projektu https://prnt.sc/22kehts

**Comment by NataliaTI** [comment]
Nadal nie wygląda to jak na projekcie. Już czas, aby zaczęło wyglądać jak na projekcie.

**Comment by KlepsydraHG** [comment]
Jaca zmień marginy między zdjęciami a copyrightem, bo sie papka robi

**Comment by jacusdestroyer** [comment]
> Jaca zmień marginy między zdjęciami a copyrightem, bo sie papka robi

okk
